const char *initialSqlStructure =
"BEGIN TRANSACTION;"
""
"create table `blocks` ("
    "`height` integer primary key,"
    "`hash` char(32) not null,"
    "`hashPrefix` integer not null,"
    "`merkleRoot` char(32) not null,"
    "`time` unsigned integer not null"
");"
""
"create index `blocksHashPrefix` on `blocks` (`hashPrefix`);"
""
"create table `transactions` ("
    "`hash` char(32) not null primary key,"
    "`hashPrefix` integer not null,"
    "`height` integer not null,"
    "`transaction` blob not null,"
    "`fee` integer not null default 0,"
    "`rejectCode` integer not null default 0,"
    "`time` unsigned integer not null default (strftime('%s', 'now'))"
");"
""
"create index `transactionsHashPrefix` on `transactions` (`hashPrefix`);"
""
"create table `nodes` ("
    "`id` integer primary key,"
    "`ip` varchar(39) not null,"
    "`port` integer not null,"
    "`services` integer not null,"
    "`date` unsigned integer not null,"
    "`testnet` bool not null,"
    "`manual` bool not null,"
    "`master` bool not null"
");"
""
"COMMIT;";
